//Types Products
export const GET_ALL = "GET_ALL";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FALSE = "GET_PRODUCT_FALSE";
export const GET_SING_PRODUCT_SUCCESS = "GET_SING_PRODUCT_SUCCESS";
export const GET_SING_PRODUCT_REQUEST = "GET_SING_PRODUCT_REQUEST";
export const GET_SING_PRODUCT_FALSE = "GET_SING_PRODUCT_FALSE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FALSE = "DELETE_PRODUCT_FALSE";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FALSE = "ADD_PRODUCT_FALSE";

export const UPDATE_PRODUCT_REQUEST = " UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = " UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FALSE = " UPDATE_PRODUCT_FALSE";

export const GET_SEARCH = "GET_SEARCH";

//Types Login
export const LOGIN_REQUEST = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALSE = "LOGIN_SUCCESS";

// export const LOGIN_SUCCESS = "LOGOUT";
export const LOGOUT = "LOGOUT";

//Types User
export const GET_ALL_USER = "GET_ALL_USER";
export const GET_USER = "GET_ALL_USER";
export const GET_USER_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_USER_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_USER_FALSE = "GET_PRODUCT_FALSE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FALSE = "DELETE_USER_FALSE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FALSE = "UPDATE_USER_RFALSE";

export const GET_SING_USER_REQUEST = "GET_SING_USER_REQUEST";
export const GET_SING_USER_SUCCESS = "GET_SING_USER_SUCCESS";
export const GET_SING_USER_FALSE = "GET_SING_USER_FALSE";

export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FALSE = "ADD_USER_FALSE";

//Types Loading
export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
